name: ci
on:
  push:
jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - 'ubuntu:20.04'
    name: "test linux ${{ matrix.distro }}"
    container: "${{ matrix.distro }}"
    env:
      DEBIAN_FRONTEND: nointeractive
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          apt-get update
          apt-get install -y \
            autoconf \
            bison \
            build-essential \
            openssl \
            re2c \
            libaspell-dev \
            libbz2-dev \
            libcurl4-gnutls-dev \
            libedit-dev \
            libenchant-dev \
            libfreetype6-dev \
            libgmp-dev \
            libicu-dev \
            libjpeg-dev \
            libkrb5-dev \
            libonig-dev \
            libpng-dev \
            libpq-dev \
            libpspell-dev \
            libreadline-dev \
            libsasl2-dev \
            libsqlite3-dev \
            libsodium-dev \
            libssl-dev \
            libtidy-dev \
            libwebp-dev \
            libxml2-dev \
            libxpm-dev \
            libxslt1-dev \
            libzip-dev
      - run: ./travis/compile.sh
      - run: make -j $(nproc) test
